# Generated by Django 4.2.30 on 2026-06-21 14:19

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['admin', 'staff']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_votes', to=settings.AUTH_USER_MODEL, verbose_name='发起人'),
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='物品名称')),
                ('found_location', models.CharField(max_length=200, verbose_name='拾取地点')),
                ('found_date', models.DateField(verbose_name='拾取日期')),
                ('description', models.TextField(blank=True, null=True, verbose_name='物品描述')),
                ('storage_location', models.CharField(max_length=200, verbose_name='存放地点')),
                ('status', models.CharField(choices=[('pending', '待认领'), ('claimed', '已认领')], default='pending', max_length=10, verbose_name='当前状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reporter', models.ForeignKey(limit_choices_to={'role__in': ['admin', 'staff']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_lost_items', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
            ],
            options={
                'verbose_name': '失物招领',
                'verbose_name_plural': '失物招领管理',
                'ordering': ['-found_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_description', models.TextField(verbose_name='认领说明')),
                ('contact_info', models.CharField(max_length=100, verbose_name='联系方式')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=10, verbose_name='审核状态')),
                ('claimant', models.CharField(blank=True, max_length=100, null=True, verbose_name='认领人')),
                ('claim_date', models.DateField(blank=True, null=True, verbose_name='认领日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_applications', to=settings.AUTH_USER_MODEL, verbose_name='认领申请人')),
                ('handler', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'staff']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_claims', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='management.lostitem', verbose_name='关联失物')),
            ],
            options={
                'verbose_name': '认领申请',
                'verbose_name_plural': '认领申请管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
