# Generated by Django 4.2.30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_user_username_alter_vote_created_by_lostitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryParkingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, verbose_name='车牌号')),
                ('visit_date', models.DateField(verbose_name='来访日期')),
                ('stay_start', models.TimeField(verbose_name='停留开始时间')),
                ('stay_end', models.TimeField(verbose_name='停留结束时间')),
                ('visit_reason', models.TextField(verbose_name='来访事由')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系人电话')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回'), ('expired', '已失效')], default='pending', max_length=10, verbose_name='申请状态')),
                ('review_remark', models.TextField(blank=True, null=True, verbose_name='审核备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='parking_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('reviewer', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'staff']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_parking_applications', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_applications', to='management.unit', verbose_name='关联房屋')),
            ],
            options={
                'verbose_name': '临时停车申请',
                'verbose_name_plural': '临时停车申请管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemporaryParkingPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_no', models.CharField(max_length=50, unique=True, verbose_name='许可编号')),
                ('status', models.CharField(choices=[('active', '有效'), ('expired', '已失效')], default='active', max_length=10, verbose_name='许可状态')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permit', to='management.temporaryparkingapplication', verbose_name='关联申请')),
            ],
            options={
                'verbose_name': '临时停车许可',
                'verbose_name_plural': '临时停车许可管理',
                'ordering': ['-generated_at'],
            },
        ),
    ]
