# Generated by Django 4.2.30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_temporaryparkingapplication_temporaryparkingpermit'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborhoodHelpPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('borrow', '求借'), ('gift', '赠送'), ('inquiry', '问询')], max_length=20, verbose_name='帖子类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('show_contact', models.BooleanField(default=False, verbose_name='是否公开联系方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_posts', to=settings.AUTH_USER_MODEL, verbose_name='发帖人')),
            ],
            options={
                'verbose_name': '邻里互助帖子',
                'verbose_name_plural': '邻里互助管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NeighborhoodHelpReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='留言内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='management.neighborhoodhelppost', verbose_name='所属帖子')),
                ('replier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_replies', to=settings.AUTH_USER_MODEL, verbose_name='留言人')),
            ],
            options={
                'verbose_name': '邻里互助留言',
                'verbose_name_plural': '邻里互助留言',
                'ordering': ['created_at'],
            },
        ),
    ]
